### ISSUE TITLE
Publishing library to Jcenter

### ISSUE THREAD

**Issue by ghost** [michaelbull/kotlin-retry#1]
Hello, 
Thanks for very cool library!
I'd like to include it to my work project, but my org. policies doesn't allow me to use bintray repositories.
Could you please add you library to Jcenter?
I'm also ready to help if you need any. 
Thanks!

**Comment by szpak** [comment]
It would be good to also enable sync with Maven Central (aka The Central Repository) in Bintray/JCenter - https://www.jfrog.com/confluence/display/BT/Syncing+with+Third-Party+Platforms

Maven Central is the only accepted repository in many organizations.

**Comment by michaelbull** [comment]
You have the right to republish the library on any artifact host you'd like (using your own coordinates) as long as the agreements in the LICENSE are followed

**Comment by szpak** [comment]
I would have to fork it and change the group id (what you also noticed) which is not the same as publishing the original project to some regular artifact repository.

However, if you created it for your own purpose and don't want to make it more popular I can understand it (in that case thanks for publishing it to GitHub at all, especially using a liberal licensing model).

**Comment by michaelbull** [comment]
What are the logistics behind using bintray's sync feature? Must I first request that maven central creates the empty coordinates on my behalf? How are the artifacts signed and is this an automatic process?

**Comment by szpak** [comment]
Uploading to Maven Central can be done automatically from Gradle, but as you already use the Bintray plugin the JCenter way should be simpler.
1. You need to create an account in Sonatype Nexus and request your project addition via Jira.
2. Add sign plugin and ensure the required pom elements are in place (developer, scm url, description, etc.)
3. Add you component to JCenter
4. Enable sync with Maven Central via Bintray UI.

The first two point are described in this [official guide](https://central.sonatype.org/pages/ossrh-guide.html). The whole process with JCenter seems to be depicted [here](https://reflectoring.io/bintray-jcenter-maven-central/).

**Comment by michaelbull** [comment]
I've switched the primary publish platform to maven central for versions 1.0.5 onwards. Thanks for your patience.

**Comment by szpak** [comment]
Great, thanks!
