### ISSUE TITLE
There is no filter function to retry only specific exceptions

### ISSUE THREAD

**Issue by gnefedev** [michaelbull/kotlin-retry#13]
In my project, I wrote

`import com.github.michaelbull.retry.ContinueRetrying
import com.github.michaelbull.retry.StopRetrying
import com.github.michaelbull.retry.policy.RetryPolicy

fun <E : Throwable> filter(test: (Throwable) -> Boolean): RetryPolicy<E> = {
    if (test(this.reason)) {
        ContinueRetrying
    } else {
        StopRetrying
    }
}`

**Comment by michaelbull** [comment]
Closing with regards to https://github.com/michaelbull/kotlin-retry/pull/14#issuecomment-762903203
