### ISSUE TITLE
New version with retryIf

### ISSUE THREAD

**Issue by szabado** [michaelbull/kotlin-retry#15]
Super short request: could you release a new version with `201a368350020b5d54cc112d0a9dd9024df467fb` included in it?

**Comment by michaelbull** [comment]
Hi @szabado, absolutely - will try and get some time this weekend hopefully if not before! Thanks

**Comment by szabado** [comment]
Awesome, thanks!

**Comment by michaelbull** [comment]
Hi @szabado, [1.0.7](https://github.com/michaelbull/kotlin-retry/releases/tag/1.0.7) is now available. Furthermore, SNAPSHOT releases will be automatically published and available [here](https://oss.sonatype.org/content/repositories/snapshots/com/michael-bull/kotlin-retry/kotlin-retry/) going forward should you find a piece of functionality in development that isn't yet released.
