### ISSUE TITLE
Graalvm incompatibility (easily fixed)

### ISSUE THREAD

**Issue by cherrydev** [michaelbull/kotlin-retry#16]
So, there's some sort of issue with Graalvm where it complains about "merging incompatible frames". It results in an error as shown in https://github.com/oracle/graal/issues/3342 but manifests when rethrowing exceptions. Thankfully, the fix is really simple and I will open up a pull request.

**Comment by michaelbull** [comment]
Fixed in https://github.com/michaelbull/kotlin-retry/releases/tag/1.0.9
