### ISSUE TITLE
Retry logic needs to have a way for the call to participate in adjusting the retry.

### ISSUE THREAD

**Issue by apatrida** [michaelbull/kotlin-retry#19]
See: https://youtrack.jetbrains.com/issue/KTOR-3544

for examples of how the call being retried may receive information to adjust the next retry delay.  

Also consider:  maximum concurrent retries, rate limiting affected by the retries.

**Comment by michaelbull** [comment]
Please can you elaborate specifically on what you would like to see implemented as a retry policy and what the current RetryPolicy framework isn't offering?

Any retry policy has access to the cumulative number of retries (used in the [`limitAttempts`](https://github.com/michaelbull/kotlin-retry/blob/1.0.9/src/main/kotlin/com/github/michaelbull/retry/policy/Limit.kt#L17) policy).
