### ISSUE TITLE
Filter retry by multiple exception types

### ISSUE THREAD

**Issue by HMaker** [michaelbull/kotlin-retry#20]
This makes it more usable
```kt
fun onException(vararg types: KClass<out Throwable>): RetryPolicy<Throwable> {
    return {
        if (types.any { it.isInstance(reason) }) ContinueRetrying else StopRetrying
    }
}
```
In some cases there is not a common base class for all exceptions that should trigger retry.

**Comment by bric3** [comment]
I agree I believe some class of errors should fail immediately, e.g. if an HTTP call gets a 403 Forbidden, it might be better to fail immediately.

**Comment by michaelbull** [comment]
With [v2.0.0](https://github.com/michaelbull/kotlin-retry/releases/tag/2.0.0) this should be as simple as:

```kotlin
import com.github.michaelbull.retry.policy.continueIf
import kotlin.reflect.KClass

public fun onException(vararg types: KClass<out Throwable>) = continueIf { (failure) -> 
    types.any { it.isInstance(failure) }
}
```

I'm going to avoid including it as part of this libraries offering as it isn't very clear to the reader that it is going to be using reflection under-the-hood with its call to `isInstance`, instead I would rather push consumers to solutions that avoid using reflection in their retry policies.
