### ISSUE TITLE
Retry with `Result`?

### ISSUE THREAD

**Issue by twyatt** [michaelbull/kotlin-retry#23]
Any plans to bring back [`retryResult`]?

It looks like it was dropped in db1c515 ("Rewrite to remove dependency on CoroutineContext").

Maybe it would make sense (for library consumers that don't use `Result`) to provide [`retryResult`] via an additional Maven artifact?

Thank you!

[`retryResult`]: https://github.com/michaelbull/kotlin-retry/blob/1.0.9/src/main/kotlin/com/github/michaelbull/retry/RetryResult.kt

**Comment by michaelbull** [comment]
Hi @twyatt - this is my plan for this week. Just like you said I'm planning to put it as a separate artifact, probably called `kotlin-retry-result`, which is why I moved the core code to the `kotlin-retry` subproject.

**Comment by twyatt** [comment]
Awesome! Thanks so much!!

**Comment by michaelbull** [comment]
Hi @twyatt - this should be available as part of https://github.com/michaelbull/kotlin-retry/releases/tag/2.0.1. Please let me know how you get on with it.

**Comment by twyatt** [comment]
Awesome, thanks a bunch! I'll give it a try soon (hopefully in the next week or two).

**Comment by twyatt** [comment]
I've been using it a bit and it's been working great! Thanks so much for the quick turnaround!
