### ISSUE TITLE
[Feature request] Add optional exception types to retry on

### ISSUE THREAD

**Issue by spypunk** [michaelbull/kotlin-retry#5]
Hi,

It would be useful to be able to define on which exception types we want to retry on.

spypunk

**Comment by michaelbull** [comment]
The [introduction section of the README](https://github.com/michaelbull/kotlin-retry#introduction) has an example of this:


```kotlin
val retryTimeouts: RetryPolicy<Throwable> = {
    if (reason is SQLDataException) ContinueRetrying else StopRetrying
}
```

**Comment by spypunk** [comment]
Great, thanks!
