### ISSUE TITLE
Is it possible to log out a line on retry?

### ISSUE THREAD

**Issue by davidb-e4s** [michaelbull/kotlin-retry#7]
It would be useful to log out a warning on a retry for monitoring connection issues that may succeed on retry. 

Is this possible?

**Comment by michaelbull** [comment]
The [example](https://github.com/michaelbull/kotlin-retry#introduction) shows a `println` in the call to `retry`.

**Comment by michaelbull** [comment]
Here is a full example in which we log the current attempt every time we retry:

```kotlin

import com.github.michaelbull.retry.context.retryStatus
import com.github.michaelbull.retry.policy.limitAttempts
import com.github.michaelbull.retry.retry
import kotlinx.coroutines.runBlocking
import java.lang.RuntimeException
import kotlin.coroutines.coroutineContext

suspend fun sum(a: Long, b: Long) {
    val attempt = coroutineContext.retryStatus.attempt

    println("attempt $attempt")

    if (attempt < 3) {
        throw RuntimeException("failed")
    } else {
        println("succeeded ${a + b}")
    }
}

fun main() = runBlocking {
    retry(limitAttempts(100)) {
        sum(5, 10)
    }
}
```

Output:

```attempt 0
attempt 1
attempt 2
attempt 3
succeeded 15
```

**Comment by davidb-e4s** [comment]
Hi, But that will only get executed when/if the call succeeds?  Not on the event of a retry being fired.

Thanks

**Comment by michaelbull** [comment]
Why would the code in `retry(policy) { ..  }` only get executed on a successful call? You pass it the code that may succeed or fail, and the policy you specify decides whether to try it again. Please refer to the example above.

**Comment by michaelbull** [comment]
@davidb-e4s did the above example help clarify things?

**Comment by davidb-e4s** [comment]
Sorry for the late reply Michael,

Yes I have it doing what I need it to do now. Thank you for your time.

Also thank you for creating this library we'll be using it for critical
inter-service http comms in our product in production soon!

Thanks

David

**Comment by michaelbull** [comment]
Glad to hear @davidb-e4s. Feel free to open another issue if you need some further clarification!
