### ISSUE TITLE
Call retry with a non-Throwable RetryPolicy

### ISSUE THREAD

**Issue by ed-george** [michaelbull/kotlin-retry#9]
It would be extremely useful for a `retry` method to exist that uses a `RetryPolicy` that does not require the use of a `Throwable`.

An example use-case of this might be when an API call is made, no error is thrown but the HTTP code is one that is unexpected

For example this code lifted from a side project of mine:

```
private val retryServerCallPolicy: RetryPolicy<NetworkResponse<*, *>> = {
        when (reason) {
            is NetworkResponse.ApiError -> when (reason.code) {
                in 500..599 -> ContinueRetrying
                else -> StopRetrying
            }
            else -> StopRetrying
        }
    }
```

Which ideally could be used in this way:

```
retry(retryServerCallPolicy + limitAttempts(3)) {
    myApiCallMethod()
}
```

I'd love to know what your thoughts are on this.

**Comment by michaelbull** [comment]
The only way the `retry` function can introspect the result of your `myApiCallMethod()` to know whether it failed or not without you explicitly providing a mechanism to do so is using one of these two generic options: 

1. Make `myApiCallMethod()` throw an exception on the bad error codes and use the `retry` function
2. Make `myApiCallMethod()` return a [`Result`](https://github.com/michaelbull/kotlin-result) (binding good status codes to Ok and bad ones to Err) then use the [`retryResult`](https://github.com/michaelbull/kotlin-retry/blob/master/src/main/kotlin/com/github/michaelbull/retry/RetryResult.kt#L29) function

The only other way around this is to make the `retry` function take some lambda that you supply to decide whether the result of the lambda is good/bad. That gets pretty ugly pretty quickly. My suggestion would be to use the `Result` type as this is designed to convey that a methods result may be a success/failure, which the `retryResult` function can then deal with appropriately.

**Comment by ed-george** [comment]
Thanks for the feedback, I will look into the `retryResult` for now and fork the code to see if I can come up with any viable alternatives to make this work. The library has been a huge help, so thanks for all your effort in creating and maintaining it
